export interface ImplantRecord {
  id: string;
  patientId: string;
  implantCategory: string;
  manufacturer: string;
  operatingSurgeon: string;
  surgeryDate: string; // ISO date string
  followUpStatus: "Scheduled" | "Overdue" | "Completed";
  alertLevel: "stable" | "review" | "attention";
  age: number;
  sex: "Male" | "Female";
  primaryDiagnosis: string;
  comorbidities: string;
  institution: string;
  modelRef: string;
  lotNumber: string;
  material: string;
  fixationType: string;
  anatomicalSite: string;
  laterality: "Left" | "Right" | "Bilateral";
  revisionHistory: string;
  complicationsLogged: number;
  lastReview: string;
  nextReview: string;
  riskLevel: "Low" | "Moderate" | "High";
}

function calcDuration(surgeryDate: string): string {
  const surgery = new Date(surgeryDate);
  const now = new Date();
  const months = Math.floor(
    (now.getTime() - surgery.getTime()) / (1000 * 60 * 60 * 24 * 30.44),
  );
  const years = Math.floor(months / 12);
  const rem = months % 12;
  if (years === 0) return `${months} months`;
  if (rem === 0) return `${years} yr`;
  return `${years} yr ${rem} mo`;
}

export const REGISTRY_DATA: ImplantRecord[] = [
  {
    id: "rec-001",
    patientId: "TH-001",
    implantCategory: "Total Hip Arthroplasty",
    manufacturer: "Zimmer Biomet",
    operatingSurgeon: "Dr. R. Krishnamurthy",
    surgeryDate: "2019-03-14",
    followUpStatus: "Overdue",
    alertLevel: "attention",
    age: 68,
    sex: "Female",
    primaryDiagnosis: "Primary osteoarthritis of hip",
    comorbidities: "Type 2 diabetes mellitus, hypertension",
    institution: "Government Rajaji Hospital, Madurai",
    modelRef: "Zimmer Biomet Taperloc Complete",
    lotNumber: "ZB-2019-HIP-0431",
    material: "Titanium alloy / Polyethylene",
    fixationType: "Cementless press-fit",
    anatomicalSite: "Hip",
    laterality: "Right",
    revisionHistory: "No prior revision",
    complicationsLogged: 1,
    lastReview: "2023-03-10",
    nextReview: "2024-03-10",
    riskLevel: "High",
  },
  {
    id: "rec-002",
    patientId: "TH-002",
    implantCategory: "Total Knee Arthroplasty",
    manufacturer: "DePuy Synthes",
    operatingSurgeon: "Dr. P. Anand",
    surgeryDate: "2021-07-22",
    followUpStatus: "Scheduled",
    alertLevel: "stable",
    age: 62,
    sex: "Male",
    primaryDiagnosis: "Bilateral knee osteoarthritis",
    comorbidities: "Hypothyroidism",
    institution: "Sri Ramachandra Institute, Chennai",
    modelRef: "DePuy Attune Revision",
    lotNumber: "DP-2021-KNEE-0877",
    material: "CoCr alloy / UHMWPE",
    fixationType: "Cemented",
    anatomicalSite: "Knee",
    laterality: "Left",
    revisionHistory: "No prior revision",
    complicationsLogged: 0,
    lastReview: "2025-07-20",
    nextReview: "2026-07-20",
    riskLevel: "Low",
  },
  {
    id: "rec-003",
    patientId: "TH-003",
    implantCategory: "Lumbar Spinal Fixation",
    manufacturer: "Stryker",
    operatingSurgeon: "Dr. S. Mehta",
    surgeryDate: "2018-11-05",
    followUpStatus: "Overdue",
    alertLevel: "attention",
    age: 55,
    sex: "Male",
    primaryDiagnosis: "L4-L5 degenerative disc disease with instability",
    comorbidities: "Obesity, chronic low back pain",
    institution: "Apollo Hospitals, Chennai",
    modelRef: "Stryker Solera 5.5/6.0",
    lotNumber: "ST-2018-SPINE-1122",
    material: "Titanium alloy",
    fixationType: "Pedicle screw-rod construct",
    anatomicalSite: "Lumbar Spine (L4-L5)",
    laterality: "Bilateral",
    revisionHistory: "Hardware adjustment 2020-06",
    complicationsLogged: 2,
    lastReview: "2023-11-01",
    nextReview: "2024-11-01",
    riskLevel: "High",
  },
  {
    id: "rec-004",
    patientId: "TH-004",
    implantCategory: "Shoulder Arthroplasty",
    manufacturer: "Smith & Nephew",
    operatingSurgeon: "Dr. R. Krishnamurthy",
    surgeryDate: "2022-02-17",
    followUpStatus: "Completed",
    alertLevel: "stable",
    age: 72,
    sex: "Female",
    primaryDiagnosis: "Rotator cuff arthropathy",
    comorbidities: "Rheumatoid arthritis (controlled)",
    institution: "MIOT International, Chennai",
    modelRef: "Smith & Nephew Journey II",
    lotNumber: "SN-2022-SHO-0345",
    material: "Titanium / Polyethylene",
    fixationType: "Reverse total shoulder",
    anatomicalSite: "Shoulder",
    laterality: "Left",
    revisionHistory: "No prior revision",
    complicationsLogged: 0,
    lastReview: "2025-02-15",
    nextReview: "2026-02-15",
    riskLevel: "Low",
  },
  {
    id: "rec-005",
    patientId: "TH-005",
    implantCategory: "Ankle Fusion",
    manufacturer: "Zimmer Biomet",
    operatingSurgeon: "Dr. V. Subramaniam",
    surgeryDate: "2020-09-30",
    followUpStatus: "Scheduled",
    alertLevel: "review",
    age: 48,
    sex: "Male",
    primaryDiagnosis: "Post-traumatic ankle arthritis",
    comorbidities: "Previous right ankle fracture (2015)",
    institution: "Kovai Medical Center, Coimbatore",
    modelRef: "Zimmer Biomet Trabecular Metal Ankle",
    lotNumber: "ZB-2020-ANK-0698",
    material: "Trabecular metal / Titanium",
    fixationType: "Cannulated screw fixation",
    anatomicalSite: "Ankle",
    laterality: "Right",
    revisionHistory: "No prior revision",
    complicationsLogged: 1,
    lastReview: "2025-03-22",
    nextReview: "2026-04-01",
    riskLevel: "Moderate",
  },
  {
    id: "rec-006",
    patientId: "TH-006",
    implantCategory: "Total Hip Arthroplasty",
    manufacturer: "Stryker",
    operatingSurgeon: "Dr. P. Anand",
    surgeryDate: "2016-05-11",
    followUpStatus: "Overdue",
    alertLevel: "review",
    age: 78,
    sex: "Female",
    primaryDiagnosis: "Femoral neck fracture, right",
    comorbidities: "Osteoporosis, atrial fibrillation",
    institution: "Madurai Meenakshi Mission Hospital",
    modelRef: "Stryker Accolade II",
    lotNumber: "ST-2016-HIP-0556",
    material: "Ti-6Al-4V / Ceramic",
    fixationType: "Cementless",
    anatomicalSite: "Hip",
    laterality: "Right",
    revisionHistory: "No prior revision",
    complicationsLogged: 1,
    lastReview: "2024-05-08",
    nextReview: "2025-05-08",
    riskLevel: "Moderate",
  },
  {
    id: "rec-007",
    patientId: "TH-007",
    implantCategory: "Total Knee Arthroplasty",
    manufacturer: "Smith & Nephew",
    operatingSurgeon: "Dr. S. Mehta",
    surgeryDate: "2023-01-09",
    followUpStatus: "Completed",
    alertLevel: "stable",
    age: 58,
    sex: "Male",
    primaryDiagnosis: "Severe valgus deformity, right knee",
    comorbidities: "Well-controlled hypertension",
    institution: "PSG Hospitals, Coimbatore",
    modelRef: "Smith & Nephew Legion Revision",
    lotNumber: "SN-2023-KNEE-1041",
    material: "CoCr / UHMWPE",
    fixationType: "Cemented stem extension",
    anatomicalSite: "Knee",
    laterality: "Right",
    revisionHistory: "No prior revision",
    complicationsLogged: 0,
    lastReview: "2025-01-06",
    nextReview: "2026-01-06",
    riskLevel: "Low",
  },
  {
    id: "rec-008",
    patientId: "TH-008",
    implantCategory: "Cervical Disc Replacement",
    manufacturer: "DePuy Synthes",
    operatingSurgeon: "Dr. R. Krishnamurthy",
    surgeryDate: "2017-08-23",
    followUpStatus: "Scheduled",
    alertLevel: "review",
    age: 44,
    sex: "Female",
    primaryDiagnosis: "C5-C6 cervical radiculopathy",
    comorbidities: "Anxiety disorder (managed)",
    institution: "Apollo Hospitals, Trichy",
    modelRef: "DePuy Synthes Prestige LP",
    lotNumber: "DP-2017-CERV-0789",
    material: "Titanium / PEEK",
    fixationType: "Anterior cervical disc replacement",
    anatomicalSite: "Cervical Spine (C5-C6)",
    laterality: "Bilateral",
    revisionHistory: "No prior revision",
    complicationsLogged: 1,
    lastReview: "2025-02-20",
    nextReview: "2026-02-20",
    riskLevel: "Moderate",
  },
  {
    id: "rec-009",
    patientId: "TH-009",
    implantCategory: "Proximal Femoral Nail",
    manufacturer: "Stryker",
    operatingSurgeon: "Dr. V. Subramaniam",
    surgeryDate: "2024-06-03",
    followUpStatus: "Completed",
    alertLevel: "stable",
    age: 81,
    sex: "Male",
    primaryDiagnosis: "Intertrochanteric femur fracture",
    comorbidities: "Chronic kidney disease Stage 2, osteoporosis",
    institution: "Government Rajaji Hospital, Madurai",
    modelRef: "Stryker Gamma3 Long Nail",
    lotNumber: "ST-2024-PFN-0312",
    material: "Titanium alloy",
    fixationType: "Intramedullary nail",
    anatomicalSite: "Proximal Femur",
    laterality: "Left",
    revisionHistory: "No prior revision",
    complicationsLogged: 0,
    lastReview: "2025-06-01",
    nextReview: "2025-12-01",
    riskLevel: "Low",
  },
  {
    id: "rec-010",
    patientId: "TH-010",
    implantCategory: "Total Hip Arthroplasty",
    manufacturer: "DePuy Synthes",
    operatingSurgeon: "Dr. P. Anand",
    surgeryDate: "2014-04-19",
    followUpStatus: "Overdue",
    alertLevel: "attention",
    age: 70,
    sex: "Female",
    primaryDiagnosis: "Advanced bilateral hip osteoarthritis",
    comorbidities: "Type 2 diabetes, peripheral neuropathy",
    institution: "Sri Ramachandra Institute, Chennai",
    modelRef: "DePuy Synthes Pinnacle",
    lotNumber: "DP-2014-HIP-0204",
    material: "Ti-6Al-4V / Polyethylene",
    fixationType: "Cementless hemispherical cup",
    anatomicalSite: "Hip",
    laterality: "Left",
    revisionHistory: "Cup revision 2018-09",
    complicationsLogged: 3,
    lastReview: "2022-04-15",
    nextReview: "2023-04-15",
    riskLevel: "High",
  },
];

export function getImplantDuration(surgeryDate: string): string {
  return calcDuration(surgeryDate);
}
